djangoEx/library_project/catalog/urls.py
from django.urls import path
from . import views

app_name = "catalog"

urlpatterns = [
    path("", views.index, name="index"),
    path("add/", views.add_book, name="add_book"),
]

djangoEx/library_project/library_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls")),
]

djangoEx/library_project/catalog/models.py
from django.db import models


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    published_date = models.DateField()

    def __str__(self):
        return self.title

djangoEx/library_project/catalog/forms.py
from django import forms
from .models import Book


class BookForm(forms.ModelForm):
    published_date = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}))

    class Meta:
        model = Book
        fields = ["title", "author", "published_date"]

djangoEx/library_project/catalog/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .models import Book
from .forms import BookForm


def index(request):
    books = Book.objects.all()
    return render(request, "catalog/index.html", {"books": books})


def add_book(request):
    if request.method == "POST":
        form = BookForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("catalog:index"))
    else:
        form = BookForm()
    return render(request, "catalog/add_book.html", {"form": form})

djangoEx/library_project/templates/catalog/add_book.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Add Book</title>
    <link rel="stylesheet" type="text/css" href="{% static 'catalog/style.css' %}">
</head>
<body>
    <div class="container">
        <h1>Add a new book</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Add book</button>
        </form>
        <a class="back-link" href="{% url 'catalog:index' %}">Back to list</a>
    </div>
</body>
</html>

djangoEx/library_project/templates/catalog/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Library Catalog</title>
    <link rel="stylesheet" type="text/css" href="{% static 'catalog/style.css' %}">
</head>
<body>
    <div class="container">
        <h1>Library Catalog</h1>
        <ul class="book-list">
            {% for book in books %}
            <li><b>{{ book.title }}</b> by <i>{{ book.author }}</i> ({{ book.published_date }})</li>
            {% endfor %}
        </ul>
        <a class="add-book-link" href="{% url 'catalog:add_book' %}">Add a new book</a>
    </div>
</body>
</html>